# Generated by Django 5.2.5 on 2025-09-02 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='forma_pago',
            field=models.CharField(choices=[('diario', 'Diario (Lunes a Sábado)'), ('semanal', 'Semanal')], default='diario', max_length=10),
        ),
    ]
