# Generated by Django 5.2.5 on 2025-09-02 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0002_prestamo_forma_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuotaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pagada', models.BooleanField(default=False)),
                ('fecha_pagada', models.DateField(blank=True, null=True)),
                ('tipo_cuota', models.CharField(choices=[('diario', 'Diario'), ('semanal', 'Semanal')], max_length=10)),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='prestamos.prestamo')),
            ],
            options={
                'unique_together': {('prestamo', 'fecha_pago')},
            },
        ),
    ]
