# Generated by Django 4.2.16 on 2025-10-19 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0003_cuotapago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuotapago',
            name='fecha_pago',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='cuotapago',
            name='pagada',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='cuotapago',
            index=models.Index(fields=['prestamo', 'fecha_pago'], name='prestamos_c_prestam_421a67_idx'),
        ),
        migrations.AddIndex(
            model_name='cuotapago',
            index=models.Index(fields=['prestamo', 'pagada'], name='prestamos_c_prestam_e2568e_idx'),
        ),
        migrations.AddIndex(
            model_name='cuotapago',
            index=models.Index(fields=['fecha_pago', 'pagada'], name='prestamos_c_fecha_p_490825_idx'),
        ),
    ]
