# Generated by Django 4.2.16 on 2025-10-19 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0004_alter_cuotapago_fecha_pago_alter_cuotapago_pagada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='estado',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='forma_pago',
            field=models.CharField(choices=[('diario', 'Diario (Lunes a Sábado)'), ('semanal', 'Semanal')], db_index=True, default='diario', max_length=10),
        ),
    ]
