# Generated by Django 4.2.16 on 2025-12-02 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoMoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Venta', 'Venta'), ('Alquiler', 'Alquiler')], default='Venta', max_length=20)),
                ('fecha_contrato', models.DateField(auto_now_add=True)),
                ('monto_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interes', models.DecimalField(decimal_places=2, default=54.47, max_digits=5)),
                ('cuotas_totales', models.IntegerField()),
                ('metodo_pago', models.CharField(choices=[('Diario', 'Diario'), ('Semanal', 'Semanal')], max_length=20)),
                ('monto_total_deuda', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('monto_cuota', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.client')),
                ('moto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.moto')),
            ],
        ),
        migrations.CreateModel(
            name='CuotaContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('fecha_vencimiento', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pagado', models.BooleanField(default=False)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='contracts.contratomoto')),
            ],
        ),
    ]
