# Generated by Django 4.2.16 on 2025-12-03 01:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratomoto',
            name='fecha_contrato',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
