# Generated by Django 4.2.16 on 2025-12-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_alter_contratomoto_fecha_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratomoto',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Pagado', 'Pagado')], default='Activo', max_length=20),
        ),
    ]
