# Generated by Django 4.2.16 on 2025-12-11 02:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imei', models.CharField(max_length=20, unique=True)),
                ('imei2', models.CharField(blank=True, max_length=20, null=True)),
                ('numero_serie', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='devices/')),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('Vendido', 'Vendido')], default='Disponible', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Contado', 'Contado'), ('Credito', 'Credito')], default='Contado', max_length=20)),
                ('fecha_venta', models.DateField(default=datetime.date.today)),
                ('monto_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('interes', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cuotas_totales', models.IntegerField(default=1)),
                ('metodo_pago', models.CharField(blank=True, choices=[('Diario', 'Diario'), ('Semanal', 'Semanal')], max_length=20, null=True)),
                ('monto_total_deuda', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('monto_cuota', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Pagado', 'Pagado')], default='Activo', max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.client')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('fecha_vencimiento', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pagado', models.BooleanField(default=False)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('metodo_pago', models.CharField(blank=True, choices=[('Yape', 'Yape'), ('Efectivo', 'Efectivo')], max_length=20, null=True)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='devices.devicesale')),
            ],
        ),
    ]
