# Generated by Django 4.2.16 on 2025-12-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicesale',
            name='icloud_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='devicesale',
            name='icloud_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='devicesale',
            name='sistema_operativo',
            field=models.CharField(choices=[('Android', 'Android'), ('IOS', 'IOS')], default='Android', max_length=20),
        ),
    ]
