# Generated by Django 4.2.16 on 2025-12-02 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=20, unique=True)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=30)),
                ('numero_motor', models.CharField(max_length=50)),
                ('numero_serie', models.CharField(max_length=50)),
                ('anio', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('condicion', models.CharField(choices=[('0km', '0km'), ('Segunda', 'Segunda')], max_length=20)),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('Alquilada', 'Alquilada'), ('Vendida', 'Vendida')], default='Disponible', max_length=20)),
            ],
        ),
    ]
