# Generated by Django 4.2.16 on 2025-12-11 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='motos/'),
        ),
    ]
