# Generated by Django 4.2.16 on 2025-12-04 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_prestamo_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuotaprestamo',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('Yape', 'Yape'), ('Efectivo', 'Efectivo')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cuotaprestamo',
            name='monto_pagado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
