# Generated by Django 4.2.16 on 2025-12-02 19:21

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, validators=[users.models.validate_gmail])),
                ('domicilio', models.TextField()),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
    ]
